# config.toml

[paths]
#relative paths from executable directory
project_file = "projects/small-cir-d2.json"
output_directory = "frames"

[rendering]
texture_width = 4742
texture_height = 1200
texture_samples = 4
arc_resolution = 25

[window]
width = 1897
height = 480

[osc]
rx_port = 8000

[output]
frame_limit = 30000
jpeg_quality = 85

[style]
default_stroke_weight = 5.1

[speed]
bpm = 120

[animation]
# Animation and effects default parameters
    [animation.power_on]
    flash_duration = 0.035
    fade_duration = 0.15

    [animation.power_off]
    fade_duration = 0.3

    [animation.background_flash]
    flash_duration = 0.035
    fade_duration = 0.15

    [transition]
    steps = 50
    frame_duration = 0.1
    wandering = 1.0
    density = 0.00001